### ISSUE TITLE
 Administrator powinien móc zarządzać firmami

### ISSUE THREAD

**Issue by mspanc** [sda-java6krk/ksiegowosc2#5]
Administrator powinien móc 

- [x] dodać nową firmę
- [x] zmienić nazwę lub NIP istniejącej firmy
- [x] usunąć firmę
- [x] wyświetlić wszystkie firmy
- [x] przypisać księgowych (wielu) do firmy

Firma powinna mieć unikalny w skali systemu NIP. Dodanie firmy o powielonym NIP powinno wyświetlać błąd.

**Comment by tpucek** [comment]
wszystkie podpunkty zrobione, zamykamy
